# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66fac4a315c3010b43517eab7253c618e85ef1eb790a9e1f4762735d4ef59cf31e421397cb34fd9358c6e0c55baf3d927aeff21662ae6c82e397025cf6d0746f

test:
  secret_key_base: 19822fd3f3b7833b1909bc9ea54ad0a40aea77aca92056b8b4ba93669194e8ddb1fc18e31ac064a36e79a791d94fd86fdaf570e3a9c2463e321cd2203c729792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
